### ISSUE TITLE
Advance (yet stupid) user could lose his tokens when voting in TemporaryVotepool.sol

### ISSUE THREAD

**Issue by yaronvel** [EthereumCommonwealth/ICO#16]
User who vote from a contract could call `Withdraw`, and in his `tokenFallback` function vote again.
This will result in loss of tokens, as `deposited[msg.sender]` is eventually reset.

This might be used by a malicious user to demonstrate a problem in ERC223.

**Comment by Dexaran** [comment]
This is not a problem of ERC223. This is a problem of implementation (mostly a ptoblem of my TemporaryVotepool.sol contract and also a problem of user who votes from contract with re-vote function implementation).
This is possible that you will end with lost tokens if you will try to cheat.

I'll update `TemporaryVotepool.sol` contract to prevent it. Thanks for feedback anyways.
